### ISSUE TITLE
Outputmode and Metadata

### ISSUE THREAD

**Issue by adrenth** [iPublications/AFAS-ProfitClass-PHP#2]
It is not possible to change the output mode or the option to leave the META data in the response. I get that the output mode should be XML since this package does only work with XML response data.

Can you add a setter for the metadata option, and make sure it's part of the <Options> element in the request?

`<Options><Outputmode>1</Outputmode><Metadata>0</Metadata></Options>`

I'm using the method `GetEncodedXML` to get the response XML, but I don't want the XSD schema.

**Comment by WietseWind** [comment]
Hi @adrenth,

This repo isn't actively under development since AFAS released their REST services some time ago. Are you sure you want to use SOAP (XML) for an AFAS integration?

**Comment by adrenth** [comment]
I see. That's what I thought already. I'm still dealing with a legacy project here. I'm aware of the REST services AFAS has provided. Until then I have provided a work-around for this "issue" myself.

Thanks for your reply.
