### ISSUE TITLE
Some points of attention

### ISSUE THREAD

**Issue by adrenth** [iPublications/AFAS-ProfitClass-PHP#3]
To make this a community package, please consider the following recommendations:

* By making all the public functions `final` it makes this package hard to extend. Be careful with the use of final and think from the 3rd party context.
* Respect the PHP PSR-2 standard for code formatting. Which makes code easy to read and consistent with the community packages (https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md)
* PHP5 support could be dropped, since it is no longer support. PHP7 or even PHP7.1 would be better.
* Make sure to document each public function. Use proper PhpDoc.

Keep up the good work!

**Comment by WietseWind** [comment]
Thanks, duly noted 👍  However, I'll close this issue: this package will no longer be maintained since AFAS is offering their REST services for quite some time now, this package will remain for legacy purposes only.
