### ISSUE TITLE
XML formatting out of date? 

### ISSUE THREAD

**Issue by nvaken** [iPublications/AFAS-ProfitClass-PHP#5]
I'm not entirely sure, but WSDL seems to suggest for ConnectorAppGetSoap and seems to work correctly:

```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:urn="urn:Afas.Profit.Services">
   <soapenv:Header/>
   <soapenv:Body>
      <urn:GetDataWithOptions>
         <!--Optional:-->
         <urn:token>?</urn:token>
         <!--Optional:-->
         <urn:connectorId>?</urn:connectorId>
         <!--Optional:-->
         <urn:filtersXml>?</urn:filtersXml>
         <urn:skip>?</urn:skip>
         <urn:take>?</urn:take>
         <!--Optional:-->
         <urn:options>?</urn:options>
      </urn:GetDataWithOptions>
   </soapenv:Body>
</soapenv:Envelope>
```

It seems that this library generates an alternative / older version of the payload? This version causes the SOAP service to return 500 statuscodes?

```
<?xml version="1.0"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <GetDataWithOptions xmlns="urn:Afas.Profit.Services">
      <token>?</token>
      <connectorId>?</connectorId>
      <filtersXml>?</filtersXml>
      <skip>?</skip>
      <take>?</take>
    </GetDataWithOptions>
  </soap:Body>
</soap:Envelope>
```

I have to admit that I'm a bit confused at this point, since the SOAP service itself seems to show examples (https://12345.afasonlineconnector.nl/profitservices/appconnectorget.asmx?op=GetDataWithOptions) which seem to comply with the XML of the lib?

**Comment by WietseWind** [comment]
The 500-codes can mean a lot of things, in case of the AFAS SOAP services it can even mean there's a validation error, but some errors / fields / connectors / services / versions just fail to return an error. Sometimes the error even isn't in the environment log. However: you might want to check the environment log (in AFAS Profit), since there might be a message containing the exception.

**Comment by nvaken** [comment]
Hi @WietseWind, thanks for the rapid response! Unfortunately, I do not have direct access to our customer's environment log and am dealing with an AFAS account manager which gave use the tokens and such. I was already afraid that the 500 error was just a generic error which could mean basically every single error. 

But to be clear, you're saying that AFAS Profit API should be able to handle the XML that uses the version with XML elements like `<token>` (see above)?

**Comment by WietseWind** [comment]
This lib. will generate the XML, based on the setters you should use. So:

1. Create a connection (object)
2. Create a connector (object) and feed it the connection object
3. Use the appropriate setters on the connection- & connectorobject
4. Execute

[Sample](<?php

namespace iPublications\Profit;
use \iPublications\Profit\Connection;
use \iPublications\Profit\AppConnectorGet;
use \Exception;

include_once (dirname(__FILE__) . '/../vendor/autoload.php');

$c = new Connection;
$c->SetTargetURL('https://12345.afasonlineconnector.nl/ProfitServices/AppConnectorGet.asmx');
$c->SetTimeout(10);

$g = new AppConnectorGet(clone $c);
$g->SetToken('AXXXXXX'); // about 64 chars?
// $g->SetConnectorId('TheGetConnectorName'); // We will specify this in the Execute method

try {
	$g->SetSkip(0);
	$g->SetTake(10);
	$g->Execute('TheGetConnectorName');
	
	$data = $g->GetResults();
	
	print_r($data);
}
catch (Exception $e){
	echo "Caught 'Exception \$e' " . PHP_EOL;
	echo "  > " . $e->GetCode() . ' - ' . $e->GetMessage();

	if($e->GetCode() == 5){
		echo "AFAS ERRORMSG:";
		print_r($g->ANTAError());
	}
})

**Comment by nvaken** [comment]
Yeah, I understand that the lib will attempt to create the appropriate XML, but I'm wondering if the XML that it produces is actually valid for AFAS. Since when I use the XML payload produced in `AFAS-ProfitClass-PHP`'s `Connection` class (see OP) in a simple command line CURL request, the service will return that 500 error. While, when using the alternative XML (also see OP), with the same options, it will actually return the expected results. So this makes me wonder if the XML generated by the lib is maybe invalid?

**Comment by WietseWind** [comment]
The AFAS webservices sometimes (can change at updates) say valid XML is invalid and the other way around. However, this lib is used in production for lots and lots of customers (on premise and AFAS Online) so that would amaze me ;) However... You never know for sure :( 

I just tried the code below on our AFAS Online environment and it works like a charm;

```php
<?php

namespace iPublications\Profit;
use \Exception;

// Use autoloader
include_once (dirname(__FILE__) . '/../iPublications/Profit/Connector.php');
include_once (dirname(__FILE__) . '/../iPublications/Profit/Connection.php');
include_once (dirname(__FILE__) . '/../iPublications/Profit/AppConnectorGet.php');

$c = new Connection;
$c->SetTargetURL('https://43854.afasonlineconnector.nl/ProfitServices/');
$c->SetTimeout(20);

$g = new AppConnectorGet($c);
$g->SetToken('D6F29665BDAXXXXXXXXXXXXXXXXXXXXXXXXXX61BA889CAE03D');
$g->SetConnectorId('ProfitCountries');

try {
	$g->SetTake(10);
	$g->SetSkip(10);
	$g->Execute();

	print_r($g->GetResults());
}
catch (Exception $e){
	echo "Caught 'Exception \$e' " . PHP_EOL;
	echo "  > " . $e->GetCode() . ' - ' . $e->GetMessage();
	if($e->GetCode() == 5){
		echo "ANTA-ERROR:";
		print_r($g->ANTAError());
	}
}
```

**Comment by nvaken** [comment]
I have absolutely no idea why it wasn't working before, but using this sample code it simply works, also with our credentials. 😕  Anyway, if it works..! Thanks for the help @WietseWind, I guess the problem was in my code before, I'll close this issue. 😄
